name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Start the cluster
        run: docker compose -f ci/docker-compose.yml up -d

      - name: Run test
        run: ./gradlew test

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2

      - name: Check Spelling
        uses: crate-ci/typos@master
